version: "3"
services:
  bot_main:
    build:
      context: .
      dockerfile: Dockerfile.main # Reference to the Dockerfile for main.py
    container_name: bot_main_service
    environment:
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo
    volumes:
      - .:/app
    restart: always

  bot_scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler # Reference to the Dockerfile for scheduler.py
    container_name: bot_scheduler_service
    environment:
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo
    volumes:
      - .:/app
    restart: always

  mongo:
    image: mongo:5.0
    container_name: mongo_service
    expose:
      - 27017
    volumes:
      - ./mongo_data:/data/db

volumes:
  mongo_data:
